'use strict';
const DB_NAME='finanzas-personales',STORE='dataset',KEY='current';
const EMPTY_FILTERS={year:'',month:'',category:'',merchant:'',payment:'',account:'',type:'',from:'',to:'',search:''};
let dataset=null,filters={...EMPTY_FILTERS},deferredInstall=null,toastTimer=null;
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)],L=globalThis.FinanceLogic;
const euro=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}),pctFmt=new Intl.NumberFormat('es-ES',{maximumFractionDigits:1}),dateFmt=new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',year:'numeric'}),monthFmt=new Intl.DateTimeFormat('es-ES',{month:'short',year:'2-digit'});

function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function dbGet(){const db=await openDB();return new Promise((resolve,reject)=>{const request=db.transaction(STORE,'readonly').objectStore(STORE).get(KEY);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}
async function dbPut(value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function dbClear(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function showToast(message){clearTimeout(toastTimer);const toast=$('#toast');toast.textContent=message;toast.classList.remove('hidden');toastTimer=setTimeout(()=>toast.classList.add('hidden'),3200)}
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function uniq(values){return[...new Set(values.filter(value=>value!==null&&value!==undefined&&value!==''))].sort((a,b)=>String(a).localeCompare(String(b),'es',{numeric:true,sensitivity:'base'}))}
function populateSelect(select,values,label='Todos'){const selected=select.value;select.innerHTML=`<option value="">${label}</option>`+values.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join('');if(values.map(String).includes(String(selected)))select.value=selected}
function periodShort(period){const[y,m]=period.split('-').map(Number);return monthFmt.format(new Date(y,m-1,1)).replace('.','')}
function signedEuro(value){return`${value>0?'+':''}${euro.format(value)}`}
function pct(value){return value===null?'No comparable':`${value>0?'+':''}${pctFmt.format(value)}%`}
function displayDate(value){return dateFmt.format(new Date(`${value}T12:00:00`))}
function filteredRows(){return dataset?L.filterRows(dataset.movements,filters):[]}
function comparisonBaseRows(){return dataset?L.filterRows(dataset.movements,{...filters,year:'',month:'',from:'',to:'',search:''},{ignoreDates:true,ignoreSearch:true}):[]}
function filterCount(){return Object.entries(filters).filter(([key,value])=>key!=='search'&&value).length}

function syncFiltersFromUI(){filters={...filters,year:$('#fYear').value,month:$('#fMonth').value,category:$('#fCategory').value,merchant:$('#fMerchant').value,payment:$('#fPayment').value,account:$('#fAccount').value,type:$('#fType').value,from:$('#fFrom').value,to:$('#fTo').value,search:$('#searchInput').value.trim()}}
function syncFiltersToUI(){const map={fYear:'year',fMonth:'month',fCategory:'category',fMerchant:'merchant',fPayment:'payment',fAccount:'account',fType:'type',fFrom:'from',fTo:'to'};for(const[id,key]of Object.entries(map))$('#'+id).value=filters[key]||'';$('#searchInput').value=filters.search||''}
function populateFilters(){if(!dataset)return;const rows=dataset.movements;populateSelect($('#fYear'),uniq(rows.map(row=>row.year)).reverse());populateSelect($('#fMonth'),uniq(rows.map(row=>row.month)).reverse());populateSelect($('#fCategory'),uniq(rows.map(row=>row.category)));populateSelect($('#fMerchant'),uniq(rows.map(row=>row.merchant)));populateSelect($('#fPayment'),uniq(rows.map(row=>row.payment)));populateSelect($('#fAccount'),uniq(rows.map(row=>row.account)));populateSelect($('#fType'),uniq(rows.map(row=>row.type)))}
function periodLabel(rows){if(!rows.length)return'Sin resultados';const dates=rows.map(row=>row.date).filter(Boolean).sort();return`${displayDate(dates[0])} – ${displayDate(dates[dates.length-1])}`}

function renderBars(container,items,emptyText){const top=items.filter(item=>item.value>0).slice(0,8),max=Math.max(1,...top.map(item=>item.value));container.innerHTML=top.length?top.map(item=>`<div class="barRow"><strong>${esc(item.name)}</strong><span>${euro.format(item.value)}</span><div class="barTrack"><div class="barFill" style="width:${item.value/max*100}%"></div></div></div>`).join(''):`<p class="muted">${emptyText}</p>`}
function selectMonth(period){filters={...filters,month:period,year:'',from:'',to:''};syncFiltersToUI();renderAll();switchView('movements');showToast(`Mostrando movimientos de ${periodShort(period)}`)}
function renderOverview(rows){
  const spend=L.spendTotal(rows),income=L.incomeTotal(rows),balance=income-spend,averages=L.averages(rows),categories=L.groupSpend(rows,'category').filter(item=>item.value>0),merchants=L.groupSpend(rows,'merchant').filter(item=>item.value>0),months=L.monthlyBalance(rows).filter(item=>item.income!==0||item.spend!==0),topMonth=[...months].sort((a,b)=>b.spend-a.spend)[0];
  $('#kpiSpend').textContent=euro.format(spend);$('#kpiPeriod').textContent=periodLabel(rows);$('#kpiIncome').textContent=euro.format(income);$('#kpiBalance').textContent=euro.format(balance);$('#kpiBalance').className=balance>0?'positive':balance<0?'negative':'';
  $('#kpiMonthAvg').textContent=euro.format(averages.monthly);$('#kpiMonthAvgNote').textContent=`${averages.months} ${averages.months===1?'mes':'meses'} con datos`;
  $('#kpiDayAvg').textContent=euro.format(averages.daily);$('#kpiDayAvgNote').textContent=`${averages.days} ${averages.days===1?'día':'días'} con movimientos`;
  $('#kpiOps').textContent=rows.length;$('#kpiAvg').textContent=euro.format(averages.operation);$('#kpiTopCat').textContent=categories[0]?.name||'—';$('#kpiTopCatAmount').textContent=categories[0]?euro.format(categories[0].value):'—';$('#kpiTopMonth').textContent=topMonth?periodShort(topMonth.period):'—';$('#kpiTopMonthAmount').textContent=topMonth?euro.format(topMonth.spend):'—';
  const maxSpend=Math.max(1,...months.map(item=>Math.max(0,item.spend)));
  $('#timeline').innerHTML=months.length?months.map(item=>`<button class="monthCol" data-month="${item.period}" type="button" aria-label="Ver ${esc(periodShort(item.period))}: ${esc(euro.format(item.spend))}"><span class="monthVal">${euro.format(item.spend)}</span><span class="monthBarWrap"><span class="monthBar" style="height:${Math.max(2,Math.max(0,item.spend)/maxSpend*100)}%"></span></span><span class="monthLabel">${esc(periodShort(item.period))}</span></button>`).join(''):'<p class="muted">Sin datos</p>';
  const maxChart=Math.max(1,...months.flatMap(item=>[Math.abs(item.income),Math.abs(item.spend),Math.abs(item.balance)]));
  $('#balanceChart').innerHTML=months.length?months.map(item=>`<button class="chartMonth" data-month="${item.period}" type="button" aria-label="${esc(periodShort(item.period))}: ingresos ${esc(euro.format(item.income))}, gastos ${esc(euro.format(item.spend))}, balance ${esc(euro.format(item.balance))}"><span class="chartBars"><i class="chartBar incomeBar" style="height:${Math.abs(item.income)/maxChart*100}%"></i><i class="chartBar spendBar" style="height:${Math.abs(item.spend)/maxChart*100}%"></i><i class="chartBar balanceBar ${item.balance<0?'negativeBar':''}" style="height:${Math.abs(item.balance)/maxChart*100}%"></i></span><small>${esc(periodShort(item.period))}</small></button>`).join(''):'<p class="muted">Sin datos</p>';
  $('#monthlyBalance').innerHTML=months.length?months.map(item=>`<button class="balanceRow" data-month="${item.period}" type="button"><strong>${esc(periodShort(item.period))}</strong><span>${euro.format(item.income)}</span><span>${euro.format(item.spend)}</span><span class="${item.balance>0?'goodText':item.balance<0?'badText':''}">${signedEuro(item.balance)}</span></button>`).join(''):'<p class="muted">Sin datos para el balance mensual.</p>';
  $$('[data-month]').forEach(button=>button.onclick=()=>selectMonth(button.dataset.month));renderBars($('#categoryBars'),categories,'Sin gasto contabilizado');renderBars($('#merchantBars'),merchants,'Sin comercios con gasto');
}

function renderCategories(rows){const categories=L.groupSpend(rows,'category').filter(item=>item.value!==0),total=L.spendTotal(rows);$('#categoryList').innerHTML=categories.length?categories.map(item=>`<button class="categoryItem" data-category="${esc(item.name)}" type="button"><strong>${esc(item.name)}</strong><span class="amount">${euro.format(item.value)}</span><small>${total?`${(item.value/total*100).toFixed(1).replace('.',',')}% del gasto`:'Sin porcentaje'}</small><small>Filtrar →</small></button>`).join(''):'<div class="padded muted">Sin categorías</div>';$$('[data-category]').forEach(button=>button.onclick=()=>{filters.category=button.dataset.category;syncFiltersToUI();renderAll();switchView('overview');showToast(`Filtro: ${filters.category}`)})}
function movementAmount(row){if(L.isIncome(row))return{value:Math.abs(row.amount),className:'incomeText',prefix:'+'};if(row.internal_transfer||row.excluded)return{value:Math.abs(row.amount),className:'mutedAmount',prefix:''};return{value:row.net_spend,className:row.net_spend<0?'refund':'',prefix:''}}
function renderMovements(rows){
  const list=[...rows].sort((a,b)=>b.date.localeCompare(a.date)||String(b.id).localeCompare(String(a.id)));$('#movementCount').textContent=`${list.length} movimientos · gasto ${euro.format(L.spendTotal(list))} · ingresos ${euro.format(L.incomeTotal(list))}`;
  $('#movementList').innerHTML=list.length?list.map(row=>{const amount=movementAmount(row),badges=[row.category,row.type,row.excluded?'Excluido del gasto':'',row.internal_transfer?'Transferencia interna':''].filter(Boolean);return`<article class="movement ${row.excluded?'excluded':''}"><div class="movementTop"><div><div class="movementMerchant">${esc(row.merchant||row.concept)}</div>${row.concept&&row.concept!==row.merchant?`<div class="movementConcept">${esc(row.concept)}</div>`:''}</div><div class="movementAmount ${amount.className}">${amount.prefix}${euro.format(amount.value)}</div></div><div class="movementMeta"><span>${displayDate(row.date)}</span>${badges.map(value=>`<span class="pill">${esc(value)}</span>`).join('')}</div><dl class="movementDetails"><div><dt>Medio de pago</dt><dd>${esc(row.payment)}</dd></div><div><dt>Cuenta / tarjeta</dt><dd>${esc(row.account)}</dd></div></dl></article>`}).join(''):'<p class="muted">No hay movimientos con estos filtros.</p>';
}

function setComparePreset(preset){const period=L.comparisonPreset(dataset?.movements||[],preset);if(!period)return;$('#aFrom').value=period.aFrom;$('#aTo').value=period.aTo;$('#bFrom').value=period.bFrom;$('#bTo').value=period.bTo;$('#compareNote').textContent=period.label;$$('.presetBtn').forEach(button=>button.classList.toggle('active',button.dataset.preset===preset));renderCompare()}
function renderCompare(){
  if(!dataset)return;const af=$('#aFrom').value,at=$('#aTo').value,bf=$('#bFrom').value,bt=$('#bTo').value;if(!af||!at||!bf||!bt||af>at||bf>bt){$('#compareSummary').innerHTML='<p class="muted">Selecciona dos periodos válidos.</p>';$('#compareCategories').innerHTML='';return}
  const result=L.comparePeriods(comparisonBaseRows(),af,at,bf,bt),diffClass=result.diff>0?'bad':result.diff<0?'good':'',balanceClass=result.balanceDiff>0?'good':result.balanceDiff<0?'bad':'';
  $('#compareSummary').innerHTML=`<div class="compareStat"><span>Gasto A</span><strong>${euro.format(result.spendA)}</strong><small>${af} → ${at}</small></div><div class="compareStat"><span>Gasto B</span><strong>${euro.format(result.spendB)}</strong><small>${bf} → ${bt}</small></div><div class="compareStat ${diffClass}"><span>Diferencia</span><strong>${signedEuro(result.diff)}</strong><small>${pct(result.pct)}</small></div><div class="compareStat"><span>Ingresos A / B</span><strong>${euro.format(result.incomeA)} / ${euro.format(result.incomeB)}</strong></div><div class="compareStat"><span>Balance A / B</span><strong>${euro.format(result.balanceA)} / ${euro.format(result.balanceB)}</strong></div><div class="compareStat ${balanceClass}"><span>Cambio de balance</span><strong>${signedEuro(result.balanceDiff)}</strong><small>A frente a B</small></div>`;
  const categories=L.categoryComparison(result.A,result.B);$('#compareCategories').innerHTML=categories.length?categories.map(row=>`<div class="compareCatRow"><strong>${esc(row.name)}</strong><span>${euro.format(row.a)}</span><span>${euro.format(row.b)}</span><span class="${row.diff>0?'badText':row.diff<0?'goodText':''}">${signedEuro(row.diff)}<small>${pct(row.pct)}</small></span></div>`).join(''):'<p class="muted">No hay gasto por categorías en estos periodos.</p>';
}

function renderAll(){if(!dataset)return;const rows=filteredRows();renderOverview(rows);renderCategories(rows);renderMovements(rows);renderCompare();const count=filterCount();$('#filterCount').textContent=count;$('#filterCount').classList.toggle('hidden',!count);const generated=dataset.generated_at?new Date(dataset.generated_at):null;$('#datasetLabel').textContent=`${dataset.movements.length} movimientos${generated&&!Number.isNaN(generated.getTime())?` · actualizado ${generated.toLocaleDateString('es-ES')}`:''}`}
function switchView(name){$$('.view').forEach(view=>view.classList.toggle('active',view.id===`view-${name}`));$$('#bottomNav button').forEach(button=>button.classList.toggle('active',button.dataset.view===name));if(name==='compare')renderCompare();window.scrollTo({top:0,behavior:'smooth'})}
function openSheet(){syncFiltersToUI();$('#filterSheet').classList.remove('hidden');document.body.classList.add('sheetOpen');$('#fYear').focus()}
function closeSheet(){$('#filterSheet').classList.add('hidden');document.body.classList.remove('sheetOpen');$('#filterBtn').focus()}
function readFile(file){if(file.text)return file.text();return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsText(file)})}
async function importFile(file,input){
  if(!file)return;try{if(file.size>25*1024*1024)throw new Error('El archivo supera 25 MB');const parsed=JSON.parse(await readFile(file)),normalized=L.normalizeDataset(parsed);await dbPut(normalized);dataset=normalized;filters={...EMPTY_FILTERS};setupDataUI();showToast(`Histórico actualizado: ${normalized.movements.length} movimientos`)}catch(error){console.error(error);showToast(error instanceof SyntaxError?'El archivo no contiene JSON válido':error.message||'No se pudo importar el archivo')}finally{if(input)input.value=''}
}
function setupDataUI(){const hasData=!!dataset;$('#emptyState').classList.toggle('hidden',hasData);$('#dashboard').classList.toggle('hidden',!hasData);$('#bottomNav').classList.toggle('hidden',!hasData);$('#filterBtn').classList.toggle('hidden',!hasData);if(!hasData)return;populateFilters();syncFiltersToUI();setComparePreset('month');renderAll()}
function updateOnlineStatus(){$('#offlineStatus').textContent=navigator.onLine?'Con conexión. Disponible sin conexión después de la primera carga.':'Sin conexión. Usando la versión guardada en este dispositivo.'}
function wire(){
  [$('#importFileEmpty'),$('#importFileSettings')].forEach(input=>input.addEventListener('change',event=>importFile(event.target.files[0],event.target)));
  $('#filterBtn').onclick=openSheet;$$('[data-close-sheet]').forEach(element=>element.onclick=closeSheet);
  ['fYear','fMonth','fCategory','fMerchant','fPayment','fAccount','fType','fFrom','fTo'].forEach(id=>$('#'+id).addEventListener('change',()=>{syncFiltersFromUI();renderAll()}));
  $('#resetFilters').onclick=()=>{filters={...EMPTY_FILTERS};syncFiltersToUI();renderAll();showToast('Filtros restablecidos')};
  let searchTimer;$('#searchInput').addEventListener('input',event=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{filters.search=event.target.value.trim();renderAll()},120)});
  $$('#bottomNav button').forEach(button=>button.onclick=()=>switchView(button.dataset.view));$('#dataBtn').onclick=()=>switchView('settings');$$('.presetBtn').forEach(button=>button.onclick=()=>setComparePreset(button.dataset.preset));
  ['aFrom','aTo','bFrom','bTo'].forEach(id=>$('#'+id).addEventListener('change',()=>{$$('.presetBtn').forEach(button=>button.classList.remove('active'));$('#compareNote').textContent='Comparación personalizada';renderCompare()}));
  $('#clearDataBtn').onclick=async()=>{if(confirm('¿Eliminar definitivamente el histórico guardado en este dispositivo?')){await dbClear();dataset=null;filters={...EMPTY_FILTERS};setupDataUI();showToast('Datos locales eliminados')}};
  window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')};window.addEventListener('online',updateOnlineStatus);window.addEventListener('offline',updateOnlineStatus);updateOnlineStatus();
}
async function registerServiceWorker(){if(!('serviceWorker'in navigator))return;try{const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});registration.update();let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing){refreshing=true;location.reload()}})}catch(error){console.error('Service Worker:',error)}}
(async function init(){wire();try{const stored=await dbGet();dataset=stored?L.normalizeDataset(stored):null;if(dataset&&JSON.stringify(dataset)!==JSON.stringify(stored))await dbPut(dataset)}catch(error){console.error(error);showToast('No se pudieron leer los datos locales')}setupDataUI();registerServiceWorker()})();
